server:
  port: 8082

spring:
  application:
    name: mbox-message
  datasource:
    url: jdbc:mysql://samin.dev:3306/message_box?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true